services:
  orders:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8007:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - orders-db
  orders-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders_dev

  celery:
    build: ./app
    command: celery --app=drf_project worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env.dev
    depends_on:
      - orders
      - orders-db
      - redis

  redis:
    image: redis:7-alpine

  flower:
    build: ./app
    command: celery flower -A drf_project --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./app/.env.dev
    depends_on:
      - orders
      - orders-db
      - redis
      - celery

volumes:
  postgres_data: